### PR TITLE
EECS-480 Fix for kalastatic/prototype/styleguide URL without index.html

### PR DESCRIPTION
**Pull request by RobLoach**
Adds an index.html when they visit `kalastatic/prototype/styleguide`.

### CODE REVIEW

**Comment by soniktrooth** [comment]
@RobLoach I don't really understand why this is necessary. Isn't it default browser behaviour when you visit a path without a file extension for it to serve an index.html if it exists?

**Comment by RobLoach** [comment]
It is, but on Pantheon for some reason, it wasn't appending a `/` at the end, resulting in broken relative links. This is what would happen...
1. You'd visit `kalastatic/prototype/styleguide`
2. A `` would then load in the browser as `kalastatic/prototype/logo.jpg` rather then the correct path of `kalastatic/prototype/styleguide/logo.jpg`

So, making sure there was a `index.html` at the end would make the browser load as `kalastatic/prototype/styleguide/index.html`, fixing the relative links. logo.jpg would then load as `kalastatic/prototype/styleguide/logo.jpg`

**Comment by soniktrooth** [comment]
@RobLoach your reasoning is good, however won't that be the same for more than just the styleguide? Your solution is limited to just `($last_arg == 'styleguide')'. Should this be broader?

**Comment by RobLoach** [comment]
Going to close this. Re-open if you run into this elsewhere.

**Pull request closed without merging**
