### PR TITLE
EECS-480 Fix the CSS paths by forcing loading index.html

### PR DESCRIPTION
**Pull request by RobLoach**
http://eecs-480-eecs.pantheon.berkeley.edu/kalastatic/prototype
http://eecs-480-eecs.pantheon.berkeley.edu/kalastatic/styleguide

### CODE REVIEW

**Comment by andrewmallis** [comment]
Why do we suddenly need to do this @RobLoach ?
Curious why things worked before and now not without index.html.

**Comment by RobLoach** [comment]
Not entirely sure. May have been a change on Pantheon. Before, we could access the following URL with the suffixing `/`:
http://test-eecs.berkeley.edu/kalastatic/prototype/styleguide/

Having that slash fixed the relative CSS paths for us. Making sure index.html is there ensures the `/` is still there, fixing the relative CSS paths.

**Comment by andrewmallis** [comment]
Thanks @RobLoach .
At first, I thought we might have had to do something in settings.php for index.html to be picked up on pantheon. Looked into other kstat+drupal projects modestly but didn't see anything.

**Comment by RobLoach** [comment]
Sent up https://github.com/kalamuna/eecs/pull/332 as a follow up.

**Pull request merged**
